name: Deploy Infra

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environmant to deploy to. dev|staging|prod'
        required: true
      stack:
        description: 'The stack to deploy. ObjectStorage|AssetAi|Scythe'
        required: true
      bootstrap:
        description: 'Bootstrap CDK'
        required: false
        type: boolean
        default: false
      context:
        description: 'Additional context to pass to the deploy command'
        required: false
        type: string
        default: ''

env:
  AWS_DEFAULT_REGION: "us-west-1"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4

      - name: validate inputs and determine AWS role
        id: validate-parse
        run: |
          # Validate environment
          if [[ ! "${{ github.event.inputs.environment }}" =~ ^(dev|staging|prod)$ ]]; then
            echo "Error: Environment must be dev, staging, or prod"
            exit 1
          fi

          # Validate stack
          if [[ ! "${{ github.event.inputs.stack }}" =~ ^(ObjectStorage|AssetAi|Scythe)$ ]]; then
            echo "Error: Stack must be ObjectStorage, AssetAi, or Scythe"
            exit 1
          fi

          # Determine AWS role based on environment
          if [[ "${{ github.event.inputs.environment }}" == "prod" ]]; then
            echo "PROD"
          elif [[ "${{ github.event.inputs.environment }}" == "staging" ]]; then
            echo "STAGING"
          else
            echo "DEV"
          fi


