name: Test Workflow
on:
  push:
    branches:
      - main
env:
  ENVIRONMENT: dev
  FOO: bar

jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      black-result: ${{ steps.exec-black.outputs.black-result
    steps:
      - name: Execute black
        id: exec-black
        run: |
          echo "black ."
          echo "black-result=true" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Run tests
        id: run-tests
        run: |
          echo "pytest ."
          echo "${{ needs.lint.outputs.black-results }}"
