name: Test Workflow
on:
  push:
    branches:
      - main
env:
  FOO: bar

jobs:
  set-context:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.context.outputs.environment }}
    steps:
      - name: Extract branch name
        id: extract-branch
        run: echo "branch-name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      - name: Set context
        id: context
        run: |
          echo "Branch name: ${{ steps.extract-branch.outputs.branch-name }}"
          if [[ "${{ steps.extract-branch.outputs.branch-name }}" == "main" ]]; then
            echo "environment=dev" >> $GITHUB_OUTPUT
          else
            echo "Unexpected branch name"
            return 1
          fi
  lint:
    runs-on: ubuntu-latest
    needs: [ set-context ]
    outputs:
      lint-result: ${{ steps.exec-black.outputs.lint-result }}
    steps:
      - name: Execute black
        id: exec-black
        run: |
          echo "black ."
          echo "lint-result=true" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest
    needs: [ set-context, lint ]
    outputs:
      test-result: ${{ steps.run-tests.outputs.test-result }}
    steps:
      - name: Run tests
        id: run-tests
        run: |
          echo "pytest ."
          echo "test-result=true" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: [ set-context, lint, test ]
    steps:
      - name: Build Container
        id: build-container
        run: |
          echo "lint result: ${{ needs.lint.outputs.lint-result }}"
          echo "test result: ${{ needs.test.outputs.test-result }}"
          echo "Building container for environment: ${{ needs.set-context.outputs.environment }}"
