name: Test Workflow
on:
  push:
    branches:
      - main
env:
  FOO: bar

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.context.outputs.environment }}
    steps:
      - name: Extract branch name
        id: extract-branch
        run: echo "branch-name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      - name: Set context
        id: context
        run: |
          echo "Branch name: ${{ steps.extract-branch.outputs.branch-name }}"
          if [[ "${{ steps.extract-branch.outputs.branch-name }}" == "main" ]]; then
            echo "environment=dev" >> $GITHUB_OUTPUT
          else
            echo "Unexpected branch name"
            return 1
          fi
  build:
    runs-on: ubuntu-latest
    needs: [ setup ]
    steps:
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 #v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4
      - name: Lint
        id: lint
        run: |
          echo "black ."
          echo "lint-result=true" >> $GITHUB_OUTPUT
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Tests
        id: run-tests
        run: |
          echo "pytest ."
          echo "test-result=true" >> $GITHUB_OUTPUT
      - name: Build Container
        id: build-container
        run: |
          echo "lint result: ${{ steps.lint.outputs.lint-result }}"
          echo "test result: ${{ steps.run-tests.outputs.test-result }}"
          echo "Building container for environment: ${{ needs.setup.outputs.environment }}"
